export const GET_REPORT_LS_REVENUE_SAGA = 'GET_REPORT_LS_REVENUE_SAGA';
export const GET_REPORT_LS_REVENUE_START = 'GET_REPORT_LS_REVENUE_START';
export const GET_REPORT_LS_REVENUE_SUCCESS = 'GET_REPORT_LS_REVENUE_SUCCESS';
export const GET_REPORT_LS_REVENUE_FAIL = 'GET_REPORT_LS_REVENUE_FAIL';

export const GET_REPORT_REVENUE_SAGA = 'GET_REPORT_REVENUE_SAGA';
export const GET_REPORT_REVENUE_START = 'GET_REPORT_REVENUE_START';
export const GET_REPORT_REVENUE_SUCCESS = 'GET_REPORT_REVENUE_SUCCESS';
export const GET_REPORT_REVENUE_FAIL = 'GET_REPORT_REVENUE_FAIL';

export const GET_REPORT_TOP_REVENUE_SAGA = 'GET_REPORT_TOP_REVENUE_SAGA';
export const GET_REPORT_TOP_REVENUE_START = 'GET_REPORT_TOP_REVENUE_START';
export const GET_REPORT_TOP_REVENUE_SUCCESS = 'GET_REPORT_TOP_REVENUE_SUCCESS';
export const GET_REPORT_TOP_REVENUE_FAIL = 'GET_REPORT_TOP_REVENUE_FAIL';