export const GET_CUSTOMER_SAGA = 'GET_CUSTOMER_SAGA';
export const GET_CUSTOMER_START = 'GET_CUSTOMER_START';
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_FAIL = 'GET_CUSTOMER_FAIL';

export const ADD_CUSTOMER_SAGA = 'ADD_CUSTOMER_SAGA';
export const ADD_CUSTOMER_START = 'ADD_CUSTOMER_START';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_FAIL = 'ADD_CUSTOMER_FAIL';

export const EDIT_CUSTOMER_SAGA = 'EDIT_CUSTOMER_SAGA';
export const EDIT_CUSTOMER_START = 'EDIT_CUSTOMER_START';
export const EDIT_CUSTOMER_SUCCESS = 'EDIT_CUSTOMER_SUCCESS';
export const EDIT_CUSTOMER_FAIL = 'EDIT_CUSTOMER_FAIL';

export const GET_TECHNICIAN_SAGA = 'GET_TECHNICIAN_SAGA';
export const GET_TECHNICIAN_START = 'GET_TECHNICIAN_START';
export const GET_TECHNICIAN_SUCCESS = 'GET_TECHNICIAN_SUCCESS';
export const GET_TECHNICIAN_FAIL = 'GET_TECHNICIAN_FAIL';

export const ADD_TECHNICIAN_SAGA = 'ADD_TECHNICIAN_SAGA';
export const ADD_TECHNICIAN_START = 'ADD_TECHNICIAN_START';
export const ADD_TECHNICIAN_SUCCESS = 'ADD_TECHNICIAN_SUCCESS';
export const ADD_TECHNICIAN_FAIL = 'ADD_TECHNICIAN_FAIL';

export const EDIT_TECHNICIAN_SAGA = 'EDIT_TECHNICIAN_SAGA';
export const EDIT_TECHNICIAN_START = 'EDIT_TECHNICIAN_START';
export const EDIT_TECHNICIAN_SUCCESS = 'EDIT_TECHNICIAN_SUCCESS';
export const EDIT_TECHNICIAN_FAIL = 'EDIT_TECHNICIAN_FAIL';

export const GET_MANAGER_SAGA = 'GET_MANAGER_SAGA';
export const GET_MANAGER_START = 'GET_MANAGER_START';
export const GET_MANAGER_SUCCESS = 'GET_MANAGER_SUCCESS';
export const GET_MANAGER_FAIL = 'GET_MANAGER_FAIL';

export const ADD_MANAGER_SAGA = 'ADD_MANAGER_SAGA';
export const ADD_MANAGER_START = 'ADD_MANAGER_START';
export const ADD_MANAGER_SUCCESS = 'ADD_MANAGER_SUCCESS';
export const ADD_MANAGER_FAIL = 'ADD_MANAGER_FAIL';

export const EDIT_MANAGER_SAGA = 'EDIT_MANAGER_SAGA';
export const EDIT_MANAGER_START = 'EDIT_MANAGER_START';
export const EDIT_MANAGER_SUCCESS = 'EDIT_MANAGER_SUCCESS';
export const EDIT_MANAGER_FAIL = 'EDIT_MANAGER_FAIL';