export const GET_VEHICLE_SAGA = 'GET_VEHICLE_SAGA';
export const GET_VEHICLE_START = 'GET_VEHICLE_START';
export const GET_VEHICLE_SUCCESS = 'GET_VEHICLE_SUCCESS';
export const GET_VEHICLE_FAIL = 'GET_VEHICLE_FAIL';

export const ADD_VEHICLE_SAGA = 'ADD_VEHICLE_SAGA';
export const ADD_VEHICLE_START = 'ADD_VEHICLE_START';
export const ADD_VEHICLE_SUCCESS = 'ADD_VEHICLE_SUCCESS';
export const ADD_VEHICLE_FAIL = 'ADD_VEHICLE_FAIL';

export const EDIT_VEHICLE_SAGA = 'EDIT_VEHICLE_SAGA';
export const EDIT_VEHICLE_START = 'EDIT_VEHICLE_START';
export const EDIT_VEHICLE_SUCCESS = 'EDIT_VEHICLE_SUCCESS';
export const EDIT_VEHICLE_FAIL = 'EDIT_VEHICLE_FAIL';