export const GET_BOOKING_SAGA = 'GET_BOOKING_SAGA';
export const GET_BOOKING_START = 'GET_BOOKING_START';
export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS';
export const GET_BOOKING_FAIL = 'GET_BOOKING_FAIL';

export const ADD_BOOKING_SAGA = 'ADD_BOOKING_SAGA';
export const ADD_BOOKING_START = 'ADD_BOOKING_START';
export const ADD_BOOKING_SUCCESS = 'ADD_BOOKING_SUCCESS';
export const ADD_BOOKING_FAIL = 'ADD_BOOKING_FAIL';

export const EDIT_BOOKING_SAGA = 'EDIT_BOOKING_SAGA';
export const EDIT_BOOKING_START = 'EDIT_BOOKING_START';
export const EDIT_BOOKING_SUCCESS = 'EDIT_BOOKING_SUCCESS';
export const EDIT_BOOKING_FAIL = 'EDIT_BOOKING_FAIL';

export const COLLECT_PAYMENT_SAGA = 'COLLECT_PAYMENT_SAGA';
export const COLLECT_PAYMENT_START = 'COLLECT_PAYMENT_START';
export const COLLECT_PAYMENT_SUCCESS = 'COLLECT_PAYMENT_SUCCESS';
export const COLLECT_PAYMENT_FAIL = 'COLLECT_PAYMENT_FAIL';