export const GET_PROFILE_SAGA = 'GET_PROFILE_SAGA';
export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const EDIT_PROFILE_SAGA = 'EDIT_PROFILE_SAGA';
export const EDIT_PROFILE_START = 'EDIT_PROFILE_START';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';

export const GET_CURRENT_USER_ID = 'GET_CURRENT_USER_ID';
export const RESET_CURRENT_USER_ID = 'RESET_CURRENT_USER_ID';

export const RESET_PROFILE_ERROR_MSG = 'RESET_PROFILE_ERROR_MSG';
