export const GET_SERVICE_SAGA = 'GET_SERVICE_SAGA';
export const GET_SERVICE_START = 'GET_SERVICE_START';
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICE_FAIL = 'GET_SERVICE_FAIL';

export const ADD_SERVICE_SAGA = 'ADD_SERVICE_SAGA';
export const ADD_SERVICE_START = 'ADD_SERVICE_START';
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';
export const ADD_SERVICE_FAIL = 'ADD_SERVICE_FAIL';

export const EDIT_SERVICE_SAGA = 'EDIT_SERVICE_SAGA';
export const EDIT_SERVICE_START = 'EDIT_SERVICE_START';
export const EDIT_SERVICE_SUCCESS = 'EDIT_SERVICE_SUCCESS';
export const EDIT_SERVICE_FAIL = 'EDIT_SERVICE_FAIL';

export const GET_PART_SAGA = 'GET_PART_SAGA';
export const GET_PART_START = 'GET_PART_START';
export const GET_PART_SUCCESS = 'GET_PART_SUCCESS';
export const GET_PART_FAIL = 'GET_PART_FAIL';

export const ADD_PART_SAGA = 'ADD_PART_SAGA';
export const ADD_PART_START = 'ADD_PART_START';
export const ADD_PART_SUCCESS = 'ADD_PART_SUCCESS';
export const ADD_PART_FAIL = 'ADD_PART_FAIL';

export const EDIT_PART_SAGA = 'EDIT_PART_SAGA';
export const EDIT_PART_START = 'EDIT_PART_START';
export const EDIT_PART_SUCCESS = 'EDIT_PART_SUCCESS';
export const EDIT_PART_FAIL = 'EDIT_PART_FAIL';